<?php

namespace Database\Seeders;

use App\Models\Sport;
use App\Models\SportEvent;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sport = new Sport;
        $sport->name = 'Angkat Berat';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 55kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 59kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 61kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 64kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 67kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 71kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 73kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 76kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 81kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Melebihi 81kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 89kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 96kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Melebihi 96kg';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Badminton';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Perseorangan Lelaki';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Beregu Lelaki';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Perseorangan Wanita';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Beregu Wanita';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Beregu Campuran';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Berbasikal';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Ujian Masa Berpasukan (60KM)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Ujian Masa Perseorangan (30KM)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '1000 Meter';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '500 Meter';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '200 Meter Sprint';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Cross Country Eliminator - MTB (1000M)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Cross Country Team Relay - MTB (4 Lap)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Cross Country Olympics - MTB (1 Jam 20 Min)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Individu Down Hill - MTB (1.5KM)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Ujian Masa Berpasukan - 30KM';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Ujian Masa Berpasukan - 20KM';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Bola Jaring';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Berpasukan';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Bola Keranjang';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '5 On 5';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Bola Sepak';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Berpasukan Lelaki';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Futsal Lelaki';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Berpasukan Wanita';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Futsal Wanita';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Bola Tampar';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Dewan';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Pantai';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Boling Padang';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Singles (21 Shots Ends)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Pairs (15 Shots Ends)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Triples (15 Ends)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Fours (15 Ends)';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'E-Sports';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Mobile Legend - Berpasukan';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'E-Football - Individu';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tekken 8 - Individu';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Golf';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Individu';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Berpasukan';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Hoki';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Berpasukan Lelaki';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Berpasukan Wanita';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Karate';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kata Individu';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kata Berpasukan';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kumite - 55kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kumite - 45kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kumite - 60kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kumite - 50kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kumite - 67kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kumite - 55kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kumite - 75kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kumite - 61kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kumite - 84kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kumite - 68kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kumite + 84kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kumite + 68kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kumite Berpasukan';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Kriket';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'T-20';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Memanah';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Recurve - Qualification Round';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Recurve - Perseorangan';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Recurve - Berpasukan';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Recurve - Berpasukan Campuran';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Compound - Perseorangan';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Compound - Qualification Round';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Compound - Berpasukan';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Compound - Berpasukan Campuran';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Muay';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kategori 42kg - 45kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kategori 45kg - 48kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kategori 48kg - 51kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kategori 51kg - 54kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kategori 54kg - 57kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kategori 57kg - 60kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kategori 60kg - 63.5kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kategori 63.5kg - 67kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kategori 67kg - 71kg';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Wai Kru (Seni Solo)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Mai Muay (Seni Duo)';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Ping Pong';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Perseorangan';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Beregu';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Berpasukan';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Beregu Campuran';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Olahraga';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '100M';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '200M';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '400M';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '800M';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '1500M';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '3000M Lari Berhalangan';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '5000M';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '100M Lari Berpagar (0.838M)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '110M Lari Berpagar (1.067M)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '400M Lari Berpagar (0.914M)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '400M Lari Berpagar (0.762M)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '4x100M Lari Berganti';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = '4x400M Lari Berganti';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Lompat Tinggi';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Lompat Jauh';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Lompat Kijang';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Lontar Peluru (7.260KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Lontar Peluru (4.00KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Lempar Cakera (2.00KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Lempar Cakera (1.00KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Merejam Lembing (800G)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Merejam Lembing (600G)';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Pencak Silat';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Solo (Bebas)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Solo (Jurus Tunggal Baku)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tempur (Ganda)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Jurus Wajib (Regu)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kelas A (45KG - 50KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kelas B (50KG - 55KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kelas C (55KG - 60KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kelas D (60KG - 65KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kelas E (65KG - 70KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kelas F (70KG - 75KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kelas G (75KG - 80KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kelas H (80KG - 85KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kelas I (85KG - 90KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Kelas J (90KG - 95KG)';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Petanque';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Perseorangan (Single)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Berdua (Double)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Bertiga (Triple)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Shooting (Single)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Berpasukan (Wajib Daftar)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Berdua Campuran (Mix Double)';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Ragbi';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Berpasukan';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Sepak Takraw';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Regu 3 Pemain';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Regu Double';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Quadrant';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Berpasukan';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Taekwando';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 46KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 49KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 53KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 54KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 57KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 58KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 62KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 63KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 67KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 68KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 73KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 74KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 80KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Tidak Melebihi 87KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Melebihi 73KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Melebihi 87KG';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Recognized Individual';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Recognized Team';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Freestyle Individual';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Recognized Mix Pair';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Freestyle Mix Pair';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Freestyle Open Team';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Tenis';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Individu';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Berpasukan';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Tinju';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Minimum Weight (46KG-48KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Fly Weight (48KG-51KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Bantam Weight (51KG-54KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Feather Weight (54KG-57KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Light Weight (57KG-60KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Light Welter (60KG-63.5KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Welter Weight (63.5KG-67KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Light Middle Weight (67KG-71KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Middle Weight (71KG-75KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Light Heavy Weight (75KG-80KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Cruiser Weight (80KG-86KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Heavy Weight (86KG-92KG)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Super Heavy Weight (Melebihi 92KG)';
        $sportEvent->save();

        $sport = new Sport;
        $sport->name = 'Wushu';
        $sport->save();

        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Taolu - Changquan';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Taolu - Nanquan';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Taolu - Taijiquan';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Taolu - Taijijian';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Taolu - Daoshu';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Taolu - Jianshu';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Taolu - Nandao';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Taolu - Nangun';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Taolu - Gunshu';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Taolu - Qiangshu';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Sanda - 52kg (>48 - ≤52 kg)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Sanda - 56kg (>52 - ≤56 kg)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Sanda - 60kg (>56 - ≤60 kg)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Sanda - 65kg (>60 - ≤65 kg)';
        $sportEvent->save();
        $sportEvent = new SportEvent;
        $sportEvent->sport_id = $sport->id;
        $sportEvent->name = 'Sanda - 70kg (>65 - ≤70 kg)';
        $sportEvent->save();
    }
}
